test with miniconda on circle

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -15,33 +15,62 @@ machine:
 
 dependencies:
 
-  # Various dependencies
-  pre:
-    - sudo -E apt-get -yq remove texlive-binaries --purge
-    - sudo apt-get update
-    - sudo apt-get install libatlas-dev libatlas3gf-base
-    - sudo apt-get install build-essential python-dev python-setuptools
+  # # Various dependencies
+  # pre:
+  #   - sudo -E apt-get -yq remove texlive-binaries --purge
+  #   - sudo apt-get update
+  #   - sudo apt-get install libatlas-dev libatlas3gf-base
+  #   - sudo apt-get install build-essential python-dev python-setuptools
+  #   # install numpy first as it is a compile time dependency for other packages
+  #   - pip install --upgrade numpy
+  #   - pip install --upgrade scipy matplotlib setuptools nose coverage sphinx pillow sphinx-gallery sphinx_rtd_theme
+  #   # Installing required packages for `make -C doc check command` to work.
+  #   - sudo -E apt-get -yq update
+  #   - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra
+  #   - pip install --upgrade cython numpydoc
+  #   - pip install --upgrade scikit-learn
+  #   - pip install pandas
 
-    - sudo apt-get install tk-dev
-    - sudo apt-get install pkg-config
-    - sudo apt-get install python-dev
-    - sudo apt-get install python-tk
+  # # The --user is needed to let sphinx see the source and the binaries
+  # # The pipefail is requested to propagate exit code
+  # override:
+  #   - python setup.py clean
+  #   - python setup.py develop
 
-    # install numpy first as it is a compile time dependency for other packages
-    - pip install --upgrade numpy
-    - pip install --upgrade scipy matplotlib setuptools nose coverage sphinx pillow sphinx-gallery sphinx_rtd_theme
-    # Installing required packages for `make -C doc check command` to work.
-    - sudo -E apt-get -yq update
-    - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra
-    - pip install --upgrade cython numpydoc
-    - pip install --upgrade scikit-learn
-    - pip install pandas
 
-  # The --user is needed to let sphinx see the source and the binaries
-  # The pipefail is requested to propagate exit code
+
   override:
-    - python setup.py clean
+    # Installing required system packages to support the rendering of math
+    # notation in the HTML documentation
+    - sudo -E apt-get -yq update
+    - sudo -E apt-get -yq remove texlive-binaries --purge
+    - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes \
+    	 install dvipng texlive-latex-base texlive-latex-extra \
+    	 texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended\
+    	 latexmk
+
+    # deactivate circleci virtualenv and setup a miniconda env instead
+    - if [[ `type -t deactivate` ]]; then
+        deactivate
+      fi
+
+    # Install dependencies with miniconda
+    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
+    	 -O miniconda.sh
+    - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
+    - export PATH="$MINICONDA_PATH/bin:$PATH"
+    - conda update --yes --quiet conda
+
+    # Configure the conda environment and put it in the path using the
+    # provided versions
+    - conda create -n $CONDA_ENV_NAME --yes --quiet python numpy scipy \
+        cython nose coverage matplotlib sphinx=1.6.2 pillow
+    - source activate testenv
+    - pip install sphinx-gallery numpydoc
+
+    # Build and install scikit-learn in dev mode
     - python setup.py develop
+
     - set -o pipefail && cd doc && make html 2>&1 | tee ~/log.txt
 test:
   # Grep error on the documentation
